### ISSUE TITLE
Validations required

### ISSUE THREAD

**Issue by YaaseenIbrahim** [YaaseenIbrahim/Caesar-Encryption#10]
# Validation for when enteredMessage is empty

When user is asked to enter message and we enter nothing or a bunch of spaces, then the bunch of spaces gets encoded, which results in the output text being spaces then the step. For example if you input a space when asked to enter msg, then you input 23 as step, then the output text would be ' bc' which is just 23 encrypted, there is no actual code. We need some validation to find our way around this.

# One word decoding

If when asked to decode something we write one word like "ghgh", then errors occur since we would need to pop this and get an encoded step. The result of these one word inputs for decoding is that the decoded text is empty. Some validation is needed here aswell.

**Comment by Aiman-Adam** [comment]
### For the heading: Validation for when **enteredMessage** is empty.
We can use a _while loop_ to check for exactly nothing (_no space no nothing_) and then make the user enter something. Spaces are tricky because we can't use a while loop there as there could be **40** spaces even.

**Comment by YaaseenIbrahim** [comment]
### Replying to: Validation for when enteredMessage is empty.

Exactly, and we cant use the numChecker() logic here aswell, by that i mean we cant make a function checking if the enteredMessage has letters or numbers. Because if someone entered like "hello world" then the space between hello and world would not count, which is an issue.

## Idea 1
Is there a way, like an array method or something, to remove all the spaces at the front of strings? For example if "         he" was entered, the spaces before the he get removed. Actually maybe the user wants the spaces too so this way of approaching it wont rly work either, but Lmk such property or method exists.

## Idea 2

We check if the encoded text only contains 1 word. If it does, then that would mean the one word is just the encoded shift, and that no text was entered as enterMessage. Problem is idk how to check if a string only contains 1 word.

## Idea 3

We check if enteredMessage has atleast 1 letter. Maybe an _If statement_. If it does contain one letter then we continue normally, otherwise we print something

Please make reference to my _Idea_ numbers when talking abt it in your next comment to this discussion.

**Comment by Aiman-Adam** [comment]
### **Replying to ideas for: Validation for when enteredMessage is empty.**

**_Idea 1_**:
I sadly do not know a way to remove the spaces but I am sure there is a way, maybe stackoverflow could help. But yes if the user intended to do so then its a problem

**_Idea 2_**:
I see that you are looking at a decoding point of view but in my opinion, I think it is more trouble some when we are encoding.

**_Idea 3_**:
We can easily check if the message contains one letter by using **_len(enteredMessage)_** and use an if statement to check if the length is 1

_This concludes my opinion to your ideas_


### **_My own Idea to check for only spaces while encoding_**
_I have a quite lengthy idea and will try my best to explain it. I personally think you are better back end so I will leave it to you to shorten the code._

**Idea sequence** :
1. We make a **_list_** that has a single space (_example: space_arr = [" "]_)
2. We check the length of the enteredMessage  using _len_ function
3. We make an array out of _enteredMessage_ using _.split()_ function
4. We use a for loop to check if enteredMessage (_it is an array coz we used split_) has spaces by using the code: IF i IN space_arr, count = count +1 (the "i" here is like the thing in for loop (for **i** in range etc...)
5. then finally we check if the count is exactly matching with the length of the eneteredMessage we checked in bullet point 2.
6. If it is matching, then the enteredMessage contains only spaces and we can easily use an if or while  loop to make the user enter something

**This may be a little confusing so please read again. If not understood, directly message me**

**Comment by YaaseenIbrahim** [comment]
### Continued: Validation for when enteredMessage is empty.

**My comments on your replys to my ideas**

**_Idea 1_**
Yeah i do not think this idea is that viable anymore compared to the other ideas that have been put forward, for that reason i will retract this idea permanently.

**_Idea 2_**
For the record it would not be troublesome when encoding either. I think i explained the method wrong, but basically even when encoding there would be a point when enteredMessage and enteredStep gets combined into one string right. If that string has only one word then we know it only has step and that there is no actual message entered. To check if it has one word we could use _split()_ or something and check if when split, there is only 1 element in the array.

Nevertheless, due to reasons i will disclose in real life insha'Allah, i want to redact this idea aswell. Please remind me to tell you what the reasoning was so that we are on the same page.

_**Idea 3**_
I don't know for sure but if we used _len()_  on enteredMessage, wouldnt the spaces also count towards the length? Or does _len()_ check for characters exclusively.

### _**My reply to your idea**_

I understood your one and i think its golden. I have a question tho, if we enter nothing (like leave it blank) then would the length of enteredMessage be 0? Or would doing len(enteredMessage) give out an error. If it is 0 then your code will work flawlessly insha'Allah.

However, i think **Idea 3** if implemented would do the same thing with less steps, as we would just check if there is atleast 1 letter, while in your thing we checking if everything is blank by doing the loop. So please clear my doubts regarding the functioning of **idea 3**.
