### ISSUE TITLE
SpaceCheck is redundant

### ISSUE THREAD

**Issue by YaaseenIbrahim** [YaaseenIbrahim/Caesar-Encryption#14]
### Could be possibly optimized
`while spaces == len(enterMessage) + 1:
            enterMessage = input("\nERROR, You left it blank! Please write something\n")    
            spaces = spaceCheck(enterMessage)`

This part is needed everytime we call spaceCheck(). I just feel like there is some optimization that should be done here, maybe putting this part inside the spaceCheck itself or something. Anyways the code works, its just that this bit is slightly redundant. Idk how to optimize it tho,

**Comment by Aiman-Adam** [comment]
I agree with you, lets put it in the space check func

**Comment by YaaseenIbrahim** [comment]
I tried and it kept giving some weird error, try it out and see if it works.
